### PR TITLE
colour scheme change referencing issue #4

### PR DESCRIPTION
**Pull request by ykl7**
@d1ndra @SaileshSriram have a look at attached screenshots and merge if colours are ok

screen shot 2016-09-04 at 2 20 46 am
screen shot 2016-09-04 at 2 20 50 am

### CODE REVIEW

**Comment by d1ndra** [comment]
@ykl7 The blue and yellow aren't really going well with each other. Try a few different shades?

**Comment by ykl7** [comment]
@d1ndra checking other colours. What do you think about moving away from the Python blue and yellow combo?

**Comment by ykl7** [comment]
@d1ndra how about these? or should i try non python b/y colour combos?

screen shot 2016-09-04 at 8 25 37 am
screen shot 2016-09-04 at 8 25 40 am

**Comment by ykl7** [comment]
@d1ndra as per @xoher suggesting black and yellow, please have a look

screen shot 2016-09-04 at 8 43 17 am
screen shot 2016-09-04 at 8 53 07 am

**Comment by ykl7** [comment]
@d1ndra Please refrain from merging till next commit. Working on adding logos as well

**Comment by ykl7** [comment]
@d1ndra Have a look and merge

screen shot 2016-09-04 at 4 07 39 pm
screen shot 2016-09-04 at 4 07 41 pm

**Comment by jiteshjha** [comment]
Close this as I've included your work in #9.

**Pull request closed without merging**
